name: Build code and call reusable deploy  workflow TEMPLATE

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  build-job:
    runs-on: windows-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '9.x'

      - name: Build code
        working-directory: sampleapp
        run: dotnet build --configuration Release

      - name: Publish code
        working-directory: sampleapp
        run: dotnet publish -c Release --property:PublishDir="${{env.DOTNET_ROOT}}\myapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          # Artifact name
          name: .net-app
          path: ${{env.DOTNET_ROOT}}\myapp

  call-reusable-workflow:
    needs: build-job
    # uses: ./.github/workflows/reusable-deploy.yml # cia kai localiai sagome
    uses: abaranauskas/shared-workflows/.github/workflows/reusabledeploy.yml@main # cia kai is kitos repo traukiam
    with:
      package-name: .net-app
      app-name: azureapp1
      deployment-slot: production
    secrets:
      azure-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
